version: "3"
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: cebolaoquest
            MYSQL_ROOT_PASSWORD: 123mudar