module.exports = (player) => ({
    name: player.name,
    level: player.level,
    exp: player.exp,
    funds: player.funds,
    statusPoints: player.statusPoints,
    proficiencyPoints: player.proficiencyPoints,
    meritPoints: player.meritPoints,
    alignment: player.alignment,
    principle: player.principle,
    class: player.class,
    valorPoints: player.valorPoints,
    species: player.species,
    sex: player.sex,
    height: player.height,
    weight: player.weight,
    locality: player.locality,
    age: player.age,
    bloodType: player.bloodType,
    birthday: player.birthday,
    selfDenomination: player.selfDenomination,
    talents: player.talents,
    likes: player.likes,
    dislikes: player.dislikes,
    abstract: player.abstract,
    userId: player.userId
})